config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks',
  }

  authenticated :user, -> user { user.admin? }  do
    mount DelayedJobWeb, at: "/delayed_job"
  end

  root 'welcome#index'

  resource :policy_agreement, only: [:create]

  resources :best_practices do
    resource :approvement, only: [:create, :destroy], module: :best_practices
  end

  get :help, to: 'welcome#help'
  get :faq, to: 'welcome#faq'

  resource :profile, only: [:show, :update] do
    get :settings
    resource :thank_you, only: [:show], module: :profiles do
      get :download
    end
    resource :subscription, module: :profiles
    resources :mailing_lists, except: [:show], controller: 'profiles/mailing_lists'
    resources :omniauth_accounts, only: [:destroy], module: 'profiles'
    resources :favourites, only: [:index, :destroy], module: :profiles
  end

  draw :admin
  draw :api

  resources :pages, only: [:show]

  namespace :press_releases do
    resources :measures, only: [:index]
    resources :urban_districts, only: [:index]
    resources :related_press_releases, only: [] do
      get :autocomplete, on: :collection
    end
    resources :form_files, only: [:new]
    resources :organizations
  end
  resources :press_releases, shallow: true do
    resources :complaints, only: [:new, :create], module: :press_releases
    resource :impression, only: [:update], module: :press_releases
    resource :approvement, only: [:create, :destroy], controller: 'press_releases/approvements'
    resource :pre_approvement, only: [:create, :destroy], controller: 'press_releases/pre_approvements'
    resource :bookmark, only: [:create, :destroy]
    resources :reposts, only: [:create, :destroy], controller: 'press_releases/reposts'
    resources :comments, only: [:index, :create, :destroy], controller: 'press_releases/comments'
    resources :bookmarked_users, only: [:index], controller: 'press_releases/bookmarked_users'
    resources :reposted_users, only: [:index], controller: 'press_releases/reposted_users'
    resources :attachments, only: [:index], controller: 'press_releases/attachments'
    resources :logs, only: [:index], controller: 'press_releases/logs'
    resources :moderators, only: [:index], controller: 'press_releases/moderators'
    resources :mailings, only: [:new, :create], controller: 'press_releases/mailings'
    resource :main_topic, only: [:edit, :update], controller: 'press_releases/main_topics'
    resource :top_list_item, only: [:create, :destroy], controller: 'press_releases/top_list_items'
    resource :award, only: [:create, :destroy], module: 'press_releases'
    resource :favourite, only: [:create, :destroy], controller: 'press_releases/favourites'
    resource :like, only: [:create, :destroy], module: :press_releases
  end

  resources :registrations, only: [:new, :create] do
    collection do
      get :organizations
    end
  end

  resources :messages, only: [] do
    patch :read
  end
  resources :message_deliveries, only: [:destroy]

  resources :support_requests, only: [:new, :create]

  resources :national_projects, only: [:index, :show] do
    get :branding
  end
  get 'brandings', to: 'national_projects#index', national_project_branding_link: true

  resources :main_topics, only: [:index, :show]
  resources :tutorials, only: [:index, :show]

  resources :regional_authorities_month_ratings, only: [:index, :create, :show, :update, :destroy] do
    # get :media
  end

  resources :placements, only: [:new, :create, :show, :edit, :update, :destroy] do
    resource :press_release_conversion, only: [:create], controller: 'placements/press_release_conversions'
  end

  resources :tag_requests, only: [:new, :create]
  resources :tags, only: [:index]
  resources :search_suggestions, only: [:index]
  resources :export_requests, only: [:new, :create]

  resources :video_albums, only: [:index, :show], shallow: true do
    resources :video_clips, only: [:show]
  end
end

app/models/main_topic.rb
class MainTopic < ApplicationRecord
  has_many :press_releases, dependent: :nullify
  has_many :main_topic_national_projects, dependent: :destroy
  has_many :national_projects, through: :main_topic_national_projects

  has_rich_text :content

  validates :name, presence: true
  validates :national_projects, presence: true

  scope :published, -> {
    where('(starts_at IS NULL OR starts_at < NOW()) AND (ends_at IS NULL OR ends_at > NOW())')
  }

  def published?
    return false if starts_at && starts_at > Time.current
    return false if ends_at && ends_at < Time.current
    true
  end
end

app/controllers/admin/main_topics/mailings_controller.rb
class Admin::MainTopics::MailingsController < AdminController
  def new
    @main_topics = MainTopic.find(params[:main_topic_ids] || [])

    if @main_topics.empty?
      render js: "alert('Не выбрана ни одна главная тема.')"
      return
    end
  end

  def create
    starts_on, ends_on = params[:period].split(' — ').map { |str| Date.parse(str) }

    if starts_on.nil? || ends_on.nil?
      render js: "alert('Нe задан период.')"
      return
    end

    press_releases = PressRelease
      .approved
      .where(main_topic_id: params[:main_topic_ids])
      .where(published_at: starts_on.to_time..ends_on.next_day.to_time)

    unless press_releases.any?
      render js: "alert('Ни одного инфоповода не найдено.')"
      return
    end

    emails = if false
      User
        .joins(:organization)
        .merge(Organization.media)
        .where(organizations: { federal_subject_id:  nil })
        .pluck(:email)
    else
      [
        'sergey@burtsev.ru',
        'a.parkhimovich@nationalpriority.ru',
        'n.lobacheva@nationalpriority.ru',
        'o.starikova@nationalpriority.ru'
      ]
    end

    emails.each do |email|
      NotifierMailer.with({
        email: email,
        starts_on: starts_on,
        ends_on: ends_on,
        press_releases: press_releases
      }).main_topics.deliver
    end
  end
end

app/controllers/admin/main_topics_controller.rb
class Admin::MainTopicsController < AdminController
  before_action :set_main_topic, only: [:edit, :update, :destroy]

  # GET /admin/main_topics
  # GET /admin/main_topics.json
  def index
    authorize [:admin, MainTopic]
    @main_topics = MainTopic.order(starts_at: 'DESC')

    @archived_mode = params[:archived] == '1'

    @main_topics = unless @archived_mode
      @main_topics.where(ends_at: [nil, Time.current...])
    else
      @main_topics.where('ends_at < ?', Time.current)
    end
  end

  # GET /admin/main_topics/1
  # GET /admin/main_topics/1.json
  def show
  end

  # GET /admin/main_topics/new
  def new
    authorize [:admin, MainTopic]
    @main_topic = MainTopic.new
  end

  # GET /admin/main_topics/1/edit
  def edit
  end

  # POST /admin/main_topics
  # POST /admin/main_topics.json
  def create
    authorize [:admin, MainTopic]
    @main_topic = MainTopic.new(main_topic_params)

    respond_to do |format|
      if @main_topic.save
        format.html { redirect_to [:admin, :main_topics], notice: 'Главная тема создана.' }
        # format.json { render :show, status: :created, location: @main_topic }
      else
        format.html { render :new }
        # format.json { render json: @main_topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/main_topics/1
  # PATCH/PUT /admin/main_topics/1.json
  def update
    respond_to do |format|
      if @main_topic.update(main_topic_params)
        format.html { redirect_to [:admin, :main_topics], notice: 'Главная тема обновлена.' }
        # format.json { render :show, status: :ok, location: @admin_main_topic }
      else
        format.html { render :edit }
        # format.json { render json: @admin_main_topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/main_topics/1
  # DELETE /admin/main_topics/1.json
  def destroy
    @main_topic.destroy
    respond_to do |format|
      format.html { redirect_to admin_main_topics_url, notice: 'Главная тема удалена.' }
      # format.json { head :no_content }
    end
  end

  def archive
    main_topic = MainTopic.find(params[:main_topic_id])
    main_topic.update(ends_at: Time.current)
    redirect_to admin_main_topics_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_main_topic
      @main_topic = MainTopic.find(params[:id])
      authorize [:admin, @main_topic]
    end

    # Only allow a list of trusted parameters through.
    def main_topic_params
      params.require(:main_topic).permit([
        :name,
        :content,
        :starts_at,
        :ends_at,
        { national_project_ids: [] }
      ])
    end
end

app/controllers/api/v1/main_topics_controller.rb
class Api::V1::MainTopicsController < ApiController
  def index
    @main_topics = MainTopic.published.order(:name)
  end
end

app/controllers/main_topics_controller.rb
class MainTopicsController < ApplicationController
  include MainTopicsListable

  def index
    @main_topics = MainTopic.published.order(:starts_at)
  end

  def show
    @main_topic = policy_scope(MainTopic).find(params[:id])
    authorize @main_topic

    @press_releases = policy_scope(PressRelease)
      .where(main_topic: @main_topic)
      .order(published_at: 'DESC')
  end
end

app/controllers/press_releases/main_topics_controller.rb
class PressReleases::MainTopicsController < ApplicationController
  before_action :set_press_release

  def edit
    @main_topics = MainTopic.published.order(:starts_at)
  end

  def update
    @press_release.update(press_release_params)
  end

  private
    def set_press_release
      @press_release = PressRelease.find(params[:press_release_id])
      authorize @press_release, :update_main_topic?
    end

    def press_release_params
      params.require(:press_release).permit(:main_topic_id)
    end
end

app/views/main_topics/index.html.erb
<% title('Главные темы') %>

<div class="container">
  <h1 class="text-primary mb-0">Главные темы –&nbsp;материал для создания федеральных новостей</h1>

  <div class="row">
    <div class="col-9">
      <div class="card card-border border-primary shadow">
        <div class="card-body pt-0 pb-7">
          <% @main_topics.each do |main_topic| %>
            <div class="d-flex py-5 border-bottom position-relative">
              <% if false %>
                <div class="mr-4" style="width: 41px;">
                  <% if national_project.avatar.attached? %>
                    <%= image_tag national_project.avatar, width: 41, height: 41 %>
                  <% end %>
                </div>
              <% end %>

              <div class="text-center flex-shrink-0" style="width: 100px; font-size: 10px; color: #A6A6A6;">
                <%= image_tag multiple_national_projects_image_url(main_topic.national_projects), width: 30, height: 30 %>

                <% if main_topic.national_projects.size < 6 %>
                  <div class="mt-2">
                    <% main_topic.national_projects.each do |national_project| %>
                      <%= national_project.short_name %><br>
                    <% end %>
                  </div>
                <% end %>
              </div>

              <div class="mt-1">
                <% if main_topic.starts_at && main_topic.ends_at %>
                  <div class="text-muted small">
                    <%= l main_topic.starts_at, format: '%-d %B' %> - <%= l main_topic.ends_at, format: '%-d %B' %>
                  </div>
                <% end %>

                <h4 class="mb-0">
                  <%= link_to main_topic.name, main_topic, class: 'text-decoration-none stretched-link' %>
                  <%#= link_to national_project.name, (@national_project_branding_link ? national_project_branding_path(national_project) : national_project_path(national_project)), class: 'text-decoration-none stretched-link' %>
                </h4>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-3">
      <%= render 'application/main_topics_list' %>
    </div>
  </div>
</div>

app/views/main_topics/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-9">
      <h1 class="text-primary mb-0"><%= title(@main_topic.name) %></h1>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-9 pb-7">
      <div class="card card-border border-primary shadow mb-2">
        <div class="card-body px-8">
          <%= @main_topic.content %>
        </div>
      </div>

      <% @press_releases.each do |press_release| %>
        <div class="card shadow mb-2" style="font-size: 12px;">
          <div class="card-body py-4">
            <div class="d-flex">
              <div class="text-center flex-shrink-0" style="width: 100px; font-size: 10px; color: #A6A6A6;">
                <%= image_tag multiple_national_projects_image_url(press_release.national_projects), width: 30, height: 30 %>

                <% if press_release.national_projects.size < 6 %>
                  <div class="mt-2">
                    <% press_release.national_projects.each do |national_project| %>
                      <%= national_project.short_name %><br>
                    <% end %>
                  </div>
                <% end %>
              </div>

              <div class="text-center flex-shrink-0" style="width: 92px;"><%= press_release.published_at.strftime('%d.%m.%y') %></div>

              <div>
                <div class="small text-secondary font-weight-light mb-1">
                  <% if press_release.all_federal_subjects? %>
                    Вся Россия
                  <% else %>
                    <% federal_subjects = press_release.federal_subjects.sort_by(&:name) %>

                    <%= federal_subjects.first.name %>
                    <% if federal_subjects.count > 1 %>
                      <%= tag.span "и ещё #{federal_subjects.count - 1}", title: federal_subjects[1..-1].map(&:name).join("\n") %>
                    <% end %>
                  <% end %>
                </div>

                <%= link_to press_release_path(press_release), class: 'press_releases_list_link' do %>
                  <% str1, str2 = truncate_two_strings(press_release.title, press_release.content.to_plain_text.remove(/\[.+?\]/).strip, 180) %>
                  <%= str1 %>
                  <% if str2.present? %>
                    <span><%= str2 %></span>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col-sm-3">
      <%= render 'application/main_topics_list' %>
    </div>
  </div>
</div>